AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    Description: The name of the environment to deploy to
    Default: staging
    AllowedValues:
      # There is no "build" environment, nor integraton
      # The "staging" environment will hold backups from
      # the govuk-one-login-staging GitHub organization,
      # and the "production" environment those from the
      # govuk-one-login GitHub organization.
      - staging
      - production
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"
Mappings:
  EnvironmentConfiguration:
    staging:
      GitHubOrganization: govuk-one-login-staging
      ImmutableGitHubOrganization: govuk-one-login-staging@184931542
    production:
      GitHubOrganization: govuk-one-login
      ImmutableGitHubOrganization: govuk-one-login@105353241
Resources:
  GitBackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketNamePrefix: !Sub "${AWS::StackName}-${Environment}"
      BucketNamespace: account-regional
      VersioningConfiguration:
        Status: Enabled
      ObjectLockEnabled: True
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule: 
          DefaultRetention: 
            Days: 15
            Mode: COMPLIANCE
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: BackupFrequency
          Value: Bihourly
        - Key: Service
          Value: github-backups
        - Key: Source
          Value: govuk-one-login/github-backups/template.yaml
        - Key: Environment
          Value: !Ref Environment
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GitBackupBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: DenyInsecureTransport
          Effect: Deny
          Principal: "*"
          Action: "s3:*"
          Resource:
            - !GetAtt GitBackupBucket.Arn
            - !Sub "${GitBackupBucket.Arn}/*"
          Condition:
            Bool:
              "aws:SecureTransport": "false"
  GitHubBackupRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role for GitHub Actions to assume
      RoleName: !Sub "${AWS::StackName}-ClientRepositoryRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated:
              - !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
          Action:
            - sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
            StringLike:
              "token.actions.githubusercontent.com:sub":
                - !Sub
                  - "repo:${SubjectClaim}/*"
                  - SubjectClaim: !FindInMap
                    - EnvironmentConfiguration
                    - !Ref Environment
                    - GitHubOrganization
                - !Sub
                  - "repo:${SubjectClaim}/*"
                  - SubjectClaim: !FindInMap
                    - EnvironmentConfiguration
                    - !Ref Environment
                    - ImmutableGitHubOrganization
      Path: /
      Policies: 
        - PolicyName: !Sub "${AWS::StackName}-ClientRepositoryRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${GitBackupBucket}"
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub "arn:aws:s3:::${GitBackupBucket}/*"
